development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(Rails.env.to_sym, :redis, :url) { "redis://localhost:6379/1" } %>
  channel_prefix: bookMyRide_production
